---

netservers:
  hosts:
    netserver:
      ansible_host: 10.254.254.1
      ansible_user: ansible
      ansible_python_interpreter: /usr/local/bin/python3
      sshd_config_path: /usr/local/etc/ssh/sshd_config
    vars:
      ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
      ansible_ssh_private_key_file: /root/.ssh/id_rsa
